"""The red-team campaign engine (ADR-0015).

Runs attack variants through the REAL inspector pipeline - the same
`build_pipeline` the gateway and the eval runner use, never a mock - and reports
which variants bypass. Two structural guarantees make the findings honest:

  1. **Real pipeline, proven live.** Before trusting any bypass, the engine runs
     every seed's PLAIN trigger and requires it to be blocked. A mock (or a
     broken pipeline) that fails to catch plaintext makes the engine refuse to
     run (RedTeamError) - so it can never "find bypasses everywhere".
  2. **No enforcement-write path.** The engine's only outputs are a report and
     `known-miss` candidate dicts. It never writes a policy, a pattern, the
     decode layer, an `active` case, or `baseline.json`. Weakening detection to
     fake a win is therefore impossible from here (ADR-0015 anti-cheat).

The loop closes through the EXISTING human gates: a human reviews a candidate and
commits it as `known-miss` (gate 1), then the builder fixes it and `olive cycle`
verifies + a human approves before the baseline rises (gate 2). The engine never
touches the corpus or the ledger.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from olive.gateway.context import SecurityContext, hash_arguments
from olive.redteam.strategies import SEEDS, STRATEGIES, AttackStrategy, SeedIntent

_ROOT = Path(__file__).resolve().parents[3]


class RedTeamError(Exception):
    """The engine refuses to run (e.g. the pipeline does not even catch a plain
    trigger). Fails closed - never report bypasses against a pipeline we cannot
    trust is live."""


@dataclass(frozen=True, slots=True)
class Bypass:
    seed_id: str
    strategy_id: str
    category: str
    payload: str
    note: str

    @property
    def key(self) -> str:
        """Stable (intent, strategy) identity for dedup - not the payload, which
        varies. A committed corpus case records this as `redteam_key`."""
        return f"{self.seed_id}:{self.strategy_id}"

    def candidate(self) -> dict:
        """A `known-miss` corpus candidate in the EVALS.md format. The engine
        produces this dict; a human reviews and commits it (gate 1). `status` is
        ALWAYS known-miss - the engine may never emit `active` (ADR-0015)."""
        cid = f"rt-{self.seed_id}-{self.strategy_id}".replace(".", "-").replace("_", "-")
        return {
            "id": cid,
            "title": f"{self.strategy_id} obfuscation of '{self.seed_id}' trigger",
            "category": self.category,
            "vector": "tool_response",
            "direction": "inbound",
            "redteam_key": self.key,
            "payload": self.payload + "\n",
            "context": {
                "role": "customer-support",
                "tool": "read_file",
                "source_trust": "untrusted",
            },
            "expected": "block",
            "status": "known-miss",
            "notes": f"auto-generated by `olive redteam`. {self.note}",
        }


@dataclass(frozen=True, slots=True)
class CampaignReport:
    seeds: int
    strategies: int
    variants: int
    bypasses: list[Bypass]
    already_filed: list[Bypass]
    novel: list[Bypass]

    def render(self) -> str:
        lines = [
            "[olive redteam] campaign complete",
            f"  seeds={self.seeds} strategies={self.strategies} variants={self.variants}",
            f"  bypasses={len(self.bypasses)} "
            f"(novel={len(self.novel)}, already filed={len(self.already_filed)})",
        ]
        for b in self.bypasses:
            tag = "filed" if b in self.already_filed else "NOVEL"
            lines.append(f"  - [{tag}] {b.key} ({b.category})")
        if not self.bypasses:
            lines.append("  no bypasses found for this seed/strategy set - the wall held.")
        return "\n".join(lines)


def _context(seed: SeedIntent) -> SecurityContext:
    return SecurityContext(
        agent_id="redteam",
        session_id="sess-redteam",
        organization_id="redteam-org",
        role=seed.role,
        declared_goal="red-team simulation",
        tool=seed.tool,
        arguments_hash=hash_arguments(None),
        direction="inbound",
        call_number=1,
        session_tool_history=(),
        source_trust=seed.source_trust,
        timestamp=SecurityContext.now(),
        requested_resource=None,
        task_resources=(),
    )


def load_known_keys(corpus_dir: str | Path) -> set[str]:
    """Collect `redteam_key` markers from committed corpus cases so a re-run does
    not re-flag an already-filed bypass. A case the engine emitted carries this
    key; hand-written cases without it are simply treated as not-yet-tracked."""
    keys: set[str] = set()
    path = Path(corpus_dir)
    if not path.is_dir():
        return keys
    for case_file in path.glob("*.yaml"):
        try:
            case = yaml.safe_load(case_file.read_text(encoding="utf-8"))
        except yaml.YAMLError:
            continue
        if isinstance(case, dict) and case.get("redteam_key"):
            keys.add(str(case["redteam_key"]))
    return keys


def _build_pipeline(policy: str):
    # Local import: the engine reuses the gateway's own pipeline assembly (the
    # real path, ADR-0015 anti-cheat) - never an engine-local stub. Imported here
    # so `import olive.redteam` does not drag in the full CLI/transport stack.
    from olive.cli import build_pipeline
    from olive.config import load_config

    return build_pipeline(load_config(_ROOT / "policies" / policy))


async def _verify_pipeline_live(pipeline, seeds: list[SeedIntent]) -> None:
    """Anti-cheat: every seed's PLAIN trigger must be blocked. If a plaintext
    trigger slips through, the pipeline is not the real one (or is broken) and we
    refuse to trust any bypass it reports."""
    for seed in seeds:
        verdict = await pipeline.run(_context(seed), seed.trigger)
        if verdict.allowed:
            raise RedTeamError(
                f"pipeline-live check failed: plain trigger for seed '{seed.id}' was "
                "allowed. Refusing to run against a pipeline that misses plaintext."
            )


async def run_campaign(
    seeds: list[SeedIntent] | None = None,
    strategies: list[AttackStrategy] | None = None,
    *,
    policy: str = "default.yaml",
    known_keys: set[str] | None = None,
) -> CampaignReport:
    """Run every (seed x strategy) variant through the real pipeline and collect
    the bypasses (variants the pipeline allowed)."""
    seeds = seeds if seeds is not None else SEEDS
    strategies = strategies if strategies is not None else STRATEGIES
    known_keys = known_keys or set()

    pipeline = _build_pipeline(policy)
    await _verify_pipeline_live(pipeline, seeds)

    bypasses: list[Bypass] = []
    variants = 0
    for seed in seeds:
        for strat in strategies:
            variants += 1
            payload = strat.mutate(seed)
            verdict = await pipeline.run(_context(seed), payload)
            if verdict.allowed:  # should have blocked -> a bypass
                bypasses.append(
                    Bypass(
                        seed_id=seed.id,
                        strategy_id=strat.id,
                        category=strat.category,
                        payload=payload,
                        note=strat.note,
                    )
                )

    already_filed = [b for b in bypasses if b.key in known_keys]
    novel = [b for b in bypasses if b.key not in known_keys]
    return CampaignReport(
        seeds=len(seeds),
        strategies=len(strategies),
        variants=variants,
        bypasses=bypasses,
        already_filed=already_filed,
        novel=novel,
    )
